name: Build

on:
  workflow_dispatch:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  ELECTRON_CACHE: $HOME/.cache/electron
  ELECTRON_BUILDER_CACHE: $HOME/.cache/electron-builder
  USE_HARD_LINKS: false
  GH_TOKEN: ${{ secrets.github_token }}
  EP_GH_IGNORE_TIME: true

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    env:
      YARN_GPG: no
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Windows
        run: yarn run electron:build -w

  build-macOS:
    name: Build macOS
    runs-on: macos-latest
    environment: build
    env:
      APPLEID: ${{ secrets.APPLEID }}
      APPLEIDPASS: ${{ secrets.APPLEIDPASS }}
      CSC_LINK: ${{ secrets.CSC_LINK }}
      CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build macOS
        run: yarn run electron:build -m

  build-ubuntu:
    name: Build Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Install libndi4_4.5.1-1_amd64.deb
        run: wget https://github.com/Palakis/obs-ndi/releases/download/4.9.0/libndi4_4.5.1-1_amd64.deb && sudo dpkg -i libndi4_4.5.1-1_amd64.deb

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build ubuntu
        run: yarn run electron:build -l
