name: Release
on:
  push:
    branches:
      - main

env:
  EP_GH_IGNORE_TIME: true

jobs:
  release:
    name: Release

    # specify the environment to select the right env variables
    environment: build

    runs-on: ubuntu-18.04

    if: "!contains(github.event.head_commit.message, 'chore(release)')"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

          # required to use our own personal access token
          # we need to use a custom PAT as other workflows
          # aren't triggered using secrets.GITHUB_TOKEN
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install libndi4_4.5.1-1_amd64.deb
        run: wget https://github.com/Palakis/obs-ndi/releases/download/4.9.0/libndi4_4.5.1-1_amd64.deb && sudo dpkg -i libndi4_4.5.1-1_amd64.deb

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: npx semantic-release
